### ISSUE TITLE
Should `add` return a `Result`?

### ISSUE THREAD

**Issue by llogiq** [llogiq/compact_arena#2]
When the arena is at capacity, further adds will panic (if debug assertions are enabled) or overwrite the first element, which is probably unwanted.

`add` should probably return a `Result<Idx*, CapacityExceeded>`. Or we leave `add` as is (or better, always panic) and introduce a new `try_add` method, but I'm not happy to make the better solution the longer one.

Perhaps:

* add returns Result
* checked_add panics
* wrapping_add overwrites

**Comment by kpp** [comment]
> When the arena is at capacity, further adds will ... or overwrite the first element, which is probably unwanted.

It's not true. I added more tests, see https://github.com/llogiq/compact_arena/pull/4

The problem is:

```
const NANO_ARENA_ITEMS: usize = 255;

pub struct TinyArena<T, B> {
    ...
    data: [T; TINY_ARENA_ITEMS],
}


assert!((i as usize) < NANO_ARENA_ITEMS);
self.data[i as usize] = item;
self.len += 1;
```

You cast `i` to `usize` and try to assign an item to `[T; 255] ` with idx=255, which will obviously fail because of out-of-range index. Max index should be `255` and the size of nano arena should be `255+1` to enable wrapping addition for u8.

But that's not all. There is a different behavior in permutation of `debug/release` and `no-default-features/uninit` which gives us the following bug:

```
cargo test --release --features uninit

---- add_256_objects stdout ----
thread 'add_256_objects' panicked at 'index out of bounds: the len is 255 but the index is 255', /home/humbug/compact_arena/src/lib.rs:503:13
note: Run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
note: Panic did not include expected string 'assertion failed: (i as usize) < NANO_ARENA_ITEMS'

failures:
    add_256_objects
```

> Or we leave add as is

It's up to you, but there is a big flow: there is no `len()` method, so the user can not manually implement `try_add`.

**Comment by llogiq** [comment]
I'm working on adding `try_add` to all arenas. `add` then becomes `self.try_add(item).unwrap()`.

**Comment by kpp** [comment]
How about 255 -> 256 for nano arena issue?

**Comment by llogiq** [comment]
We now have try_add on all arenas, so closing this.
